### ISSUE TITLE
Partial works: https://ig.beparanoid.de/u/

### ISSUE THREAD

**Issue by juanpc2018** [libredirect/libredirect#436]
https://ig.beparanoid.de/u/
```

           ◸―――――――――――――――――――――――――――――――――――――◹
     ···<  |        500. That's an error.        |  >···
           ◺―――――――――――――――――――――――――――――――――――――◿


 ╱  Are you visiting this website? Not sure what's going on?  ╲
 ╲             You might want to come back later.             ╱



Error: No profile info in the preloader.
    at /home/bibliogram/bibliogram/src/lib/collectors.js:74:12
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getUserAndQuota (/home/bibliogram/bibliogram/src/site/api/routes.js:21:28)
    at async Object.code (/home/bibliogram/bibliogram/src/site/api/routes.js:114:29)
```

**Comment by EdwardLangdon** [comment]
This happens because the Bibliogram project is discontinued. The existing instances can only load Instagram posts not profiles. 

We are looking for other FLOSS alternatives.

In the upcoming versions, it is planned to support only redirect posts unless a good alternative is found out.
